# Generated by Django 4.2.1 on 2023-06-03 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('part_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('location', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=20)),
                ('price_usd', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_usd_price', models.IntegerField()),
                ('client_dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Tienda_de_repuestos.client')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Tienda_de_repuestos.product')),
            ],
        ),
    ]
