# Generated by Django 4.2.1 on 2023-06-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tienda_de_repuestos', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
