# Generated by Django 4.2.1 on 2023-06-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tienda_de_repuestos', '0003_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='App_Tienda_de_repuestos/products'),
        ),
    ]
