# Generated by Django 4.2 on 2023-06-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tienda_de_repuestos', '0004_remove_client_lastname_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('msg', models.TextField()),
            ],
        ),
    ]
