# Generated by Django 4.2 on 2023-06-11 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tienda_de_repuestos', '0005_contat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contat',
            new_name='Contact',
        ),
    ]
