# Generated by Django 4.2 on 2023-06-11 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tienda_de_repuestos', '0006_rename_contat_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
